# behaviors:
#   RaceCar:
#     trainer_type: ppo
#     hyperparameters:
#       batch_size: 10
#       buffer_size: 100
#       learning_rate: 3.0e-4
#       beta: 5.0e-4
#       epsilon: 0.2
#       lambd: 0.99
#       num_epoch: 2
#       learning_rate_schedule: linear
#       beta_schedule: constant
#       epsilon_schedule: linear
#     network_settings:
#       normalize: false
#       hidden_units: 128
#       num_layers: 3
#     reward_signals:
#       extrinsic:
#         gamma: 0.99
#         strength: 0.1
#       gail:
#         gamma: 0.99
#         strength: 1.0
#         demo_path: "C:/Users/KIIT/Desktop/Learning Environments/NeuralNitro-AI/Demo/demo.demo"
#     behavioral_cloning:
#       demo_path: "C:/Users/KIIT/Desktop/Learning Environments/NeuralNitro-AI/Demo/demo.demo"
#       strength: 1.0
#     max_steps: 360000
#     time_horizon: 64
#     summary_freq: 10000
behaviors:
  RaceCar:
    trainer_type: ppo
    hyperparameters: 
      batch_size: 256
      buffer_size: 10240
      learning_rate: 5.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 0.1
      gail:
        gamma: 0.99
        strength: 1.0
        demo_path: "C:/Users/KIIT/Desktop/Learning Environments/NeuralNitro-AI/Demo/demo.demo"
    behavioral_cloning: 
      demo_path: "C:/Users/KIIT/Desktop/Learning Environments/NeuralNitro-AI/Demo/demo.demo"
      strength: 1.0
    max_steps: 700000
    time_horizon: 64
    summary_freq: 20000