behaviors:
  RaceCar:
    trainer_type: ppo
    hyperparameters: 
      batch_size: 256
      buffer_size: 10240
      learning_rate: 5.0e-5
      beta: 5.0e-4
      epsilon: 0.3
      lambd: 0.995
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 3
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 0.5
      gail:
        gamma: 0.99
        strength: 0.5
        demo_path: Demo\NN-RightChicane.demo
    behavioral_cloning: 
      demo_path: Demo\NN-RightChicane.demo
      strength: 0.5
    max_steps: 5000000
    checkpoint_interval: 250000
    keep_checkpoints: 100
    time_horizon: 64
    summary_freq: 50000
    init_path: Curriculum\3-LeftChicane-5000023.pt